plugins {
    id("java-library")
    id("antlr")
    id("me.champeau.jmh") version "0.7.2"
    id("com.adarshr.test-logger") version "4.0.0"
}

dependencies {
    antlr("org.antlr:antlr4:4.13.1")

    implementation("io.avaje:avaje-jsonb:2.3")
    annotationProcessor("io.avaje:avaje-jsonb-generator:2.3")
}

testlogger {
    showFullStackTraces = false
    showPassed = false
    showStandardStreams = false
}

jmh {
    warmupIterations = 2
    iterations = 5
    fork = 1
}

jar {
    excludes += "/source_images/*"
}

tasks.register("generateLexerSource", AntlrTask) {
    source = file("src/main/antlr/com/faforever/neroxis/lua/LuaLexer.g4")
    outputDirectory = file("build/generated-src/antlr/main/com/faforever/neroxis/lua")
    arguments += ['-package', 'com.faforever.neroxis.lua', '-visitor', '-no-listener']
}

tasks.named("generateGrammarSource", AntlrTask) {
    dependsOn += tasks.named("generateLexerSource")
    source = file("src/main/antlr/com/faforever/neroxis/lua/LuaParser.g4")
    arguments += ['-lib', 'build/generated-src/antlr/main/com/faforever/neroxis/lua', '-package', 'com.faforever.neroxis.lua', '-visitor', '-no-listener']
}