# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generator Jar Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Generator Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Jar
        run: ./gradlew --stacktrace shadowJar --no-daemon -PgeneratorVersion=${{ github.event.inputs.version }}

      - name: Archive shadow jar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generator-shadow-jar
          path: ./**/NeroxisGen_*.jar

  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
      fail-fast: false
    name: Package ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Package with Gradle
        run: ./gradlew -x test --stacktrace jpackage --no-daemon -PgeneratorVersion=${{ github.event.inputs.version }}

      - name: Archive jpackage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-${{ matrix.os }}
          path: ./**/jpackage
  
  release:
    runs-on: ubuntu-latest
    needs:
      - package
      - build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          preserve_order: true
          tag_name: ${{ github.event.inputs.version }}
          release_name: NeroxisGen_${{ github.event.inputs.version }}
          generate_release_notes: true
          files: |
            generator-shadow-jar/*.jar
            jpackage-windows-latest/*
            jpackage-ubuntu-latest/*
            jpackage-macOS-latest/*